spring.application.name=ecomart

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.retry.max-attempts=20
spring.ai.openai.retry.backoff.initial-interval=10
spring.ai.openai.retry.backoff.max= 300

logging.level.org.springframework.ai.chat.client,advisor=DEBUG